name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  

jobs:

  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image # push The image to the docker hub
      run: docker build . --file ./fluentd/Dockerfile --tag ${{ secrets.DOCKER_USER }}/fluentdwindows:${{github.run_number}}
    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USER }}/fluentdwindows:${{github.run_number}}

